* [v] reorg: documents 30 mins

* [ ] qa: 4 units

* [ ] qa 增加`python main.py --review`功能，复习当天的 units

* [ ] 在做检测时，写出 unit 出自哪里

* [v] 在 224 机器上尝试断点 nccl

    feedback:

    1. 224 机器上的 nccl cuda-gdb 依然很慢，起码需要半个小时以上才能 hit 断点

    2. 通过 printf 法，看到`op128.h`文件里主要调用的是`ld_volatile_global()`

        在 print 的 log 中，`in ld_volatile_global()...`与 nccl 的 perf 数据交替出现，数据测试没有问题，说明在传输数据过程中确实用到了`ld_volatile_global()`

    3. 在`ld_volatile_global()`中设置断点，经过半个多小时后，断点被 hit

        看到的调用栈如下：

        ```
        ld_volatile_global() - op128.h:295
        Primitives::loadStepValue() - prims_simple.h:106 -> 116
        Primitives::loadRecvConn() - prims_simple.h:477 -> 496
        Primitives::Primitives() - prims_simple.h:574 -> 646
        RunWorkBatch::run() - common.h:280 -> ?
        RunWorkBatch<AllReduce_Sum_f32_RING_SIMPLE>.run() -> build/obj/device/gensrc/all_reduce_sum_f32.cu:15
        ncclKernelMain() - common.h:312 -> 369
        AllReduce_Sum_f32_RING_LL build/obj/device/gensrc/all_reduce_sum_f32.cu:3
        ```

        hit 断点时，output 界面仍有 perf data 输出，但 bandwith 等数据都是 0. 说明 perf data 和 ld_volatile_global() 可能是异步执行的，并且 perf data 可能会用到 ld volatile global 的数据。

    4. 在 ld_volatile_global() 处恢复运行，disable 断点后，nccl perf data 最后仍能正常输出。说明前面的数据 0 并不是真的 0，只是数据很小没有显示出来。

        同时还说明，前几轮的小数据量 perf 有可能没有调用到 ld_volatile_global()。

        很可能是 8 bytes - 1048576 bytes 这个范围内。

    5. nccl 很可能起了 46183 个 device 线程

* [ ] 调研 sglang start up